### ISSUE TITLE
Service 'burrow' failed to build: ADD failed: stat

### ISSUE THREAD

**Issue by drewjocham** [linkedin/Burrow#325]
I am getting trying to test this pull and I used the configuration provided (thank you) but I am getting the following error:

> ERROR: Service 'burrow' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder804244187/burrow: no such file or directory

In the `docker-compose.yml` I have the following:
```
zookeeper:
  image: confluent/zookeeper
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka:0.9.0.0-1
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    - KAFKA_ADVERTISED_HOST_NAME
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_DELETE_TOPIC_ENABLE=true
    - KAFKA_LOG_RETENTION_HOURS=1
    - KAFKA_MESSAGE_MAX_BYTES=10000000
    - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
    - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
    - KAFKA_NUM_PARTITIONS=2
    - KAFKA_DELETE_RETENTION_MS=1000


kafka-manager:
  image: sheepkiller/kafka-manager:latest
  ports:
    - "9000:9000"
  links:
    - zookeeper
    - kafka
  environment:
    ZK_HOSTS: zookeeper:2181
    APPLICATION_SECRET: letmein
    KM_ARGS: -Djava.net.preferIPv4Stack=true
```
DockerFile
```
FROM iron/go
MAINTAINER LinkedIn Burrow "https://github.com/linkedin/Burrow"

WORKDIR /app
ADD burrow /app/
ADD burrow.toml /etc/burrow/

CMD ["/app/burrow", "--config-dir", "/etc/burrow"]
```

output when running `docker-compose up`:

```
WARNING: The PWD variable is not set. Defaulting to a blank string.
Building burrow
Step 1/6 : FROM iron/go
 ---> c05f82fa066a
Step 2/6 : MAINTAINER LinkedIn Burrow "https://github.com/linkedin/Burrow"
 ---> Using cache
 ---> d996174a5656
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 847414401fb0
Step 4/6 : ADD burrow /app/
ERROR: Service 'burrow' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder804244187/burrow: no such file or directory
```

docker info
```

Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155dc95315
ID: 4JHP:3KUK:WUDH:2QXW:DMB7:KAXW:D552:QFKY:ZDY4:LESV:WSNI:CQAV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 37
 System Time: 2018-01-11T13:17:42.2610224Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
