### ISSUE TITLE
How to set header in notifier http request

### ISSUE THREAD

**Issue by xxf0925** [linkedin/Burrow#416]
hi, I want to use the http notifier to send message, but I need to set http header, how can I do this?

**Comment by maxtuzz** [comment]
After checking the source code it looks like this functionality exists. However, it isn't documented anywhere. 

```
for header, value := range viper.GetStringMapString("notifier." + module.name + ".headers") {
		req.Header.Set(header, value)
	}
```

So it looks like you just need to add a `headers` property under your notifier config. How that should be formatted in toml I'm unsure. Since I'm working in the codebase now I'll do a quick test and get back to you.

**Comment by maxtuzz** [comment]
try: 

```toml
[notifier.myhttp]
...
...
[notifier.myhttp."headers"]
headerName="headerValue"
```
