### ISSUE TITLE
Load sensitive config credentials via secrets/env variable

### ISSUE THREAD

**Issue by weeco** [linkedin/Burrow#486]
The burrow configuration requires SASL credentials (username + password). I don't want to put any credentials into my Kubernetes configmap.

Thus I am wondering if it Is possible to load parts of the configuration (e. g. SASL profile passwords) from environment variables, so that I don't need to put credentials into the configuration? This way I could mount a kubernetes secret as environment variable which then will be loaded on startup by burrow.

```toml
    [tls.prd-tls-profile]
    certfile="certificate.crt"
    keyfile="keyfile.key"
    cafile="rootcerts.crt"
    noverify=false
    [sasl.prd-sasl-profile]
    username="myname"
    password="sekrit"
    handshake-first=false
```
