### ISSUE TITLE
Failed to get zk lock, trying to acquire a lock twice

### ISSUE THREAD

**Issue by cdenneen** [linkedin/Burrow#747]
Running build off master branch:

```
{"level":"warn","ts":1648046723.7982295,"msg":"failed to get zk lock","type":"coordinator","name":"notifier","error":"zk: trying to acquire a lock twice"}
```

**Comment by cdenneen** [comment]
Seeing the zk lock error flooding after received a bunch of these:

```
{"level":"warn","ts":1648046696.1697328,"msg":"error in OffsetResponse","type":"module","coordinator":"cluster","class":"kafka","name":"gw","sarama_error":"kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.","broker":3,"topic":"qa-logs-apms-apjson","partition":2}
{"level":"warn","ts":1648046696.1699715,"msg":"error in OffsetResponse","type":"module","coordinator":"cluster","class":"kafka","name":"gw","sarama_error":"kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.","broker":3,"topic":"dev-logs-electionsapi-syslog","partition":1}
{"level":"warn","ts":1648046696.169988,"msg":"error in OffsetResponse","type":"module","coordinator":"cluster","class":"kafka","name":"gw","sarama_error":"kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.","broker":3,"topic":"production-refeed-logs-iis","partition":1}
{"level":"warn","ts":1648046696.1701412,"msg":"error in OffsetResponse","type":"module","coordinator":"cluster","class":"kafka","name":"gw","sarama_error":"kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.","broker":3,"topic":"dev-logs-apnewsnr-apfeed","partition":2}
```

I can try to restart burrow but not sure what the cause here is.
Checking the consumers I see `burrow-consumer_kafka` in `ERR` state and a large TotalLag

**Comment by cdenneen** [comment]
```
{"level":"info","ts":1648046313.133591,"msg":"send loop terminated: err=<nil>","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.1572301,"msg":"Connected to 10.x.x.x:2181","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.221864,"msg":"authentication failed: zk: session has been expired by the server","type":"coordinator","name":"zookeeper"}
{"level":"error","ts":1648046325.2221205,"msg":"session expired","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.2221758,"msg":"stopping evaluations","type":"coordinator","name":"notifier"}
{"level":"info","ts":1648046325.2317216,"msg":"Connected to 10.x.x.y:2181","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.2325819,"msg":"starting session","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.2409785,"msg":"authenticated: id=72057644841238557, timeout=6000","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1648046325.2410588,"msg":"re-submitting `0` credentials after reconnect","type":"coordinator","name":"zookeeper"}
{"level":"warn","ts":1648046325.448404,"msg":"failed to get zk lock","type":"coordinator","name":"notifier","error":"zk: trying to acquire a lock twice"}
{"level":"warn","ts":1648046326.1202273,"msg":"failed to get zk lock","type":"coordinator","name":"notifier","error":"zk: trying to acquire a lock twice"}
{"level":"warn","ts":1648046326.241202,"msg":"failed to get zk lock","type":"coordinator","name":"notifier","error":"zk: trying to acquire a lock twice"}
```

**Comment by cdenneen** [comment]
Nevermind. Even after a consumer rename the TotalLag is still over 6M:
`ERR | burrow-consumer_kafka2 | 6,356,007 | gw`

**Comment by cdenneen** [comment]
```toml
[general]
access-control-allow-origin="*"

[logging]
level="info"

[zookeeper]
servers=["ZKHOST"]
timeout=6

[client-profile.profile]
kafka-version="2.1.0"
client-id="burrow-client"
tls="tlsprofile"

[tls.tlsprofile]
certfile="certificate.crt"
keyfile="keyfile.key"
noverify=false

[cluster.gw]
class-name="kafka"
client-profile="profile"
servers=["BROKER"]
topic-refresh=60
offset-refresh=30
groups-reaper-refresh=30

[consumer.consumer_kafka2]
class-name="kafka"
cluster="gw"
servers=["BROKER"]
client-profile="profile"
start-latest=false
offsets-topic="__consumer_offsets"
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[consumer.consumer_zk]
class-name="kafka_zk"
cluster="gw"
servers=["ZKHOST"]
zookeeper-timeout=30
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"
```
